version: '3'
services:
  my-app:
    image: python-webapp:2.0
    restart: always
    ports:
      - 8080:80

  database:
    image: mysql-database:1.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306    
    environment:
      - MYSQL_ROOT_PASSWORD=movie123

volumes:
  mysql-data:
    driver: local 
  