version: '3'
services:
  my-app:
    image: public.ecr.aws/f6e8d9s2/webapp:latest 
    ports:
      - 80:80
    deploy:
      replicas: 6

  database:
    image: public.ecr.aws/f6e8d9s2/moviedb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306    
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=movie123
    deploy:
      replicas: 1

volumes:
  mysql-data:

networks:
  frontend:
  backend:
